version: "3.8"
services:
  api:
    build: .
    image: vaquerosback:latest
    container_name: vaquerosback_api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped

