name = "vaquerosback-workers"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[vars]
NOTION_DATABASE_ID_USER = ""
NOTION_DATABASE_ID_PAREJA = ""
NOTION_DATABASE_ID_ENCUENTRO = ""
NOTION_DATABASE_ID_PLAN = ""
NOTION_DATABASE_ID_COMENTARIOS = ""
GOOGLE_CLIENT_ID = ""

# Secret vars (no se versionan):
# wrangler secret put NOTION_API_KEY
# wrangler secret put JWT_SECRET

